"""alembic revision

Revision ID: f228a9a247b2
Revises: f8cbdc3dbdd8
Create Date: 2024-11-01 15:18:23.044551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f228a9a247b2'
down_revision: Union[str, None] = 'f8cbdc3dbdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
